import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { loadSource, parseFrontmatter } from "./parse.js";
import type { SkillPack } from "./types.js";

function collectFiles(dir: string, base: string = dir, out: Record<string, string> = {}): Record<string, string> {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) collectFiles(p, base, out);
    else out[relative(base, p).split("\\").join("/")] = readFileSync(p, "utf8");
  }
  return out;
}

/** Bundle a skill source directory into one portable JSON envelope. */
export function packSource(srcDir: string): SkillPack {
  const { ir } = loadSource(srcDir);
  return { skillpack: 1, name: ir.name, version: ir.version, irHash: ir.irHash, files: collectFiles(srcDir) };
}

export function writePack(pack: SkillPack, outFile: string): void {
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, JSON.stringify(pack, null, 2) + "\n", "utf8");
}

export interface UnpackResult {
  outDir: string;
  warnings: string[];
}

/**
 * Reverse import. Accepts either a .skillpack envelope (verbatim restore) or
 * an existing single-format skill directory (SKILL.md [+ tools/]) and writes
 * a skill.src skeleton. Capabilities cannot be inferred from prose — the
 * generated yaml carries TODOs and conservative defaults.
 */
export function unpackInto(input: string, outDir: string): UnpackResult {
  const warnings: string[] = [];
  const dst = join(outDir, "skill.src");
  mkdirSync(dst, { recursive: true });

  if (input.endsWith(".skillpack")) {
    const pack = JSON.parse(readFileSync(input, "utf8")) as SkillPack;
    if (pack.skillpack !== 1 || typeof pack.files !== "object") {
      throw new Error(`${input}: not a skillpack envelope`);
    }
    for (const [rel, content] of Object.entries(pack.files)) {
      const p = join(dst, ...rel.split("/"));
      mkdirSync(dirname(p), { recursive: true });
      writeFileSync(p, content, "utf8");
    }
    return { outDir: dst, warnings };
  }

  const md = join(input, "SKILL.md");
  if (!existsSync(md)) throw new Error(`no SKILL.md found in ${input} — unpack expects a skill directory`);
  const { fm } = parseFrontmatter(readFileSync(md, "utf8"));
  const rawName = typeof fm.name === "string" && fm.name ? fm.name : basename(input);
  const name = rawName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "imported-skill";
  const description = typeof fm.description === "string" ? fm.description : "";
  if (!description) warnings.push("no description in frontmatter — add one (harnesses route on it)");

  const yaml = [
    "# Generated by skillc unpack from " + input,
    "# TODO: review needs — capabilities cannot be inferred from prose alone.",
    "name: " + name,
    "version: 0.1.0",
    "description: " + JSON.stringify(description),
    "needs: [read-files, write-files]",
    "targets:",
    "  claude-code: {}",
    "  codex: {}",
    "  dsh: {}",
    ""
  ].join("\n");
  writeFileSync(join(dst, "skill.yaml"), yaml, "utf8");
  writeFileSync(join(dst, "SKILL.md"), readFileSync(md, "utf8"), "utf8");

  const toolsDir = join(input, "tools");
  if (existsSync(toolsDir)) {
    for (const [rel, content] of Object.entries(collectFiles(toolsDir))) {
      const p = join(dst, "tools", ...rel.split("/"));
      mkdirSync(dirname(p), { recursive: true });
      writeFileSync(p, content, "utf8");
    }
  }
  return { outDir: dst, warnings };
}
